import "./components/slider.js";
import "./components/directions-scroll.js";
import "./components/comments.js";
import "./components/menu.js";
import "./components/faq.js";
import "./components/certificates.js";
import "./components/video.js";
import "./components/header.js";
import "./components/form.js";
